#!/bin/bash

funct_spript_info(){
cat << EOF
    # Script Name	:
    # Author:
    # Created					:
    # Last Modified:
    # Version					:1.0

    # Modifications:

    # Description		:
EOF
echo -e "\e[1;33m--------------------------------------------------------------------------------\e[0m"
}


#################################
# Start of procedures/functions #
#################################

################
# Main Program #
################

clear
sleep 1 

# variable

{
    
}
# rm -rf 6ope_logs.sh
rm -rf $0
## End of Script
